//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcGymOtomasyonu.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOdeme
    {
        public int OId { get; set; }
        public string Ay { get; set; }
        public string Uye { get; set; }
        public Nullable<int> Miktar { get; set; }
    }
}
